[theme]
primaryColor = "#1e293b"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#0f172a"
font = "sans serif"

[server]
maxUploadSize = 5

[client]
toolbarMode = "minimal"
